### PR TITLE
WIP - Time to review and and update code styles again

### PR DESCRIPTION
**Pull request by ashahba**
If you aren't done, please add the `wip` label until you're ready for review.

If you are adding a new template or mlt command/flag ensure that is is documented in the [docs/features.md](https://github.com/IntelAI/mlt/tree/master/docs/features.md) file.

## Reviewer Checklist

 - [ ] Do you understand it?
 - [ ] Is it correct?
 - [ ] Is it safe?
 - [ ] Is it legally compliant?
 - [ ] Is it robust?
 - [ ] Is it simple?
 - [ ] Is it tested?
 - [ ] Is it documented?
 - [ ] Is the style consistent?

See [the reviewer guide](docs/reviews.md) for more detail on each check.

### CODE REVIEW

**Comment by s1113950** [comment]
I'm confused; if every PR that comes in passes our style tests why should we keep having to do this? It takes away from the original owner who wrote these lines and makes it harder to find them and ask questions about certain parts if need be. If our style needs to be fixed we should fix our lint tests in accordance with whatever needs fixing

**Comment by ashahba** [comment]
Yes, for some reason we don't enforced on our tests.
Once this one is in, we should make it so that it checks for style on tests as well 🙂

**Comment by s1113950** [comment]
```
lint:
	@echo "Linting with flake8..."
	@tox -e py2-lint -e py3-lint
``` 
it does check for style:

```
- run:
          name: lint tests
          command: |
            make lint
```

**Comment by ashahba** [comment]
And I guess we overwrite it (in `tox.ini`) and it only check style for `mlt` folder:
```
commands =
    # install commands first, then test commands
    pip wheel -w /tmp/wheelhouse -r requirements.txt -r requirements-dev.txt
    dev: pip wheel -w /tmp/wheelhouse -e .
    pip install --no-index --find-links=/tmp/wheelhouse -r requirements.txt -r requirements-dev.txt mlt
    # can't seem to make editable install use wheels and not result in bad `mlt` package entry point
    # so copy good package entry_point made by wheel, then make editable and write over bad entry_point
    dev: /bin/cp {envdir}/bin/mlt /tmp/mlt_good_entrypoint.py
    dev: pip install -e .
    dev: /bin/cp /tmp/mlt_good_entrypoint.py {envdir}/bin/mlt

    lint: flake8 mlt
    unit: py.test -v --cov-report term-missing --cov-fail-under=90 --cov {envsitepackagesdir}/mlt --cov-report html {env:TESTOPTS:} {env:TESTFILES:tests/unit}
    e2e: py.test -vv {env:TESTOPTS:} {env:TESTFILES:tests/e2e}
    coverage: coverage report --show-missing --omit='./.tox/*','./tests/*'
```

**Comment by ashahba** [comment]
So the actual `flake8` command only runs against `mlt` folder!

**Comment by ashahba** [comment]
Closing this in favor of #303

**Pull request closed without merging**
