### PR TITLE
Added option to output trained data as SavedModel

### PR DESCRIPTION
**Pull request by CraigSterrett**
Added the option to output the trained data in SavedModel format
to support tf-serving.

Signed-off-by: Ubuntu <ubuntu@ip-172-31-38-22.us-west-2.compute.internal>

fixes #{issue_num_here_if_applicable}

If you aren't done, please add the `wip` label until you're ready for review.

If you are adding a new template or mlt command/flag ensure that is is documented in the [docs/features.md](https://github.com/IntelAI/mlt/tree/master/docs/features.md) file.

## Reviewer Checklist

 - [ ] Do you understand it?
 - [ ] Is it correct?
 - [ ] Is it safe?
 - [ ] Is it legally compliant?
 - [ ] Is it robust?
 - [ ] Is it simple?
 - [ ] Is it tested?
 - [ ] Is it documented?
 - [ ] Is the style consistent?

See [the reviewer guide](docs/reviews.md) for more detail on each check.

### CODE REVIEW

**Comment by poussa** [comment]
@CraigSterrett Why is the entire main.py file showing as a replacement. Must be a whitespace or other formating issue. Can you re-format the file so it just shows the added/changed lines.

**Comment by CraigSterrett** [comment]
I will look into that, I am not sure what happened, on the system I pushed from I see 105 lines changed.  It’s still WIP since I need to add and test the making SavedModel format optional, hopefully that will get fixed when I re-push the file.

ubuntu@ip-172-31-38-22:~/git/mlt/mlt-templates/horovod$ diff main.py ~/git/temp/mlt/mlt-templates/horovod/main.py | wc -l
105

**Comment by poussa** [comment]
@CraigSterrett LGTM now

**Comment by nqn** [comment]
Closing due to project deprecation

**Pull request closed without merging**
