### PR TITLE
New tf-distributed which uses MonitoredTrainingSession

### PR DESCRIPTION
**Pull request by tonyreina**
wip

The Distributed TensorFlow projects now recommend using a MonitoredTraining session. This automatically handles the checkpoints, failover, and coordination between the nodes. 

I've re-written the tf-distributed template to use a Monitored Session. I've also broken out the model code into a file called model.py. Right now it is just done as a dictionary; Krishna has a class implementation that it better (I'm going to eventually migrate to it, but wanted to push the code for review now since the monitored session is important.)

Only known bug is with the checkpoints directory. I think I need to add KVC to allow the code to use a common checkpoint directory for all nodes. I'm not sure how to do this.

## Reviewer Checklist

 - [ ] Do you understand it?
 - [ ] Is it correct?
 - [ ] Is it safe?
 - [ ] Is it legally compliant?
 - [ ] Is it robust?
 - [ ] Is it simple?
 - [ ] Is it tested?
 - [ ] Is it documented?
 - [ ] Is the style consistent?

See [the reviewer guide](docs/reviews.md) for more detail on each check.

### CODE REVIEW

**Comment by tonyreina** [comment]
I've also re-written tf-dist-mnist in the same fashion. In this case I refactored the data loader as a separate script (data.py).  Again, I like Krishna's way to handling this as a python class rather than a dictionary (which is what I did). However, this code works and is fairly simple to follow. Hopefully, someone can help convert the dictionary to a class??

Only error I still get is with the checkpoints. I think I need to setup KVC and declare the checkpoint_directory as a NFS or S3 folder. I'm hoping someone can help with that part too.

Current code works but doesn't save checkpoints. Also, I'll hopefully get to add TensorBoard images in the next version. If the checkpoint directory is setup properly, then regular TensorBoard stuff should work.

**Comment by tonyreina** [comment]
Just wanted to see if someone could please review. This will definitely make the distributed templates easier to use for the data scientists since it refactors the main.py into a model.py and data.py.

**Comment by mas-dse-greina** [comment]
Just bumping this again to see if someone can review for the PR. Thanks.

-Tony

**Comment by ashahba** [comment]
@tonyreina Thanks for the PR.
Ping me directly so we can fix the PR and have it pass the tests before we can review and merge it.

Thanks.

**Comment by s1113950** [comment]
@tonyreina @ashahba what's the status of this?

**Comment by ashahba** [comment]
@s1113950 I'll review and update here.

**Comment by tonyreina** [comment]
Thanks. Also, when you update it can you remove the `import logging` and change the `logging.info` statements to `tf.logging.info` statements. That should prevent duplicate logs.

**Comment by s1113950** [comment]
@ashahba what's the status of this?

**Comment by nqn** [comment]
Closing due to project deprecation

**Pull request closed without merging**
