### PR TITLE
adding W503 to ignore list for pep8 and also fix W504 and W605 errors

### PR DESCRIPTION
**Pull request by ashahba**
We are getting a bunch of style errors since W504 is enforced by default now and W503 was supposed to added to ignore list by default but that doesn't seem to work.

So this is what this fix is about.

Read more about it here: https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

### CODE REVIEW

**Comment by ashahba** [comment]
I can skip the examples like we used to, that should be fine @dmsuehir

**Comment by ashahba** [comment]
@dmsuehir I added `examples` folder to the ignore list for style checking 🙂

**Comment by dmsuehir** [comment]
@ashahba weird, I thought it was already there.  Thanks

**Comment by ashahba** [comment]
Only [examples/horovod_unet](https://github.com/IntelAI/mlt/pull/464/files#diff-b91f3d5bd63fcd17221b267e851608e8L31) was in the list 🙂

**Pull request merged**
