### PR TITLE
Using intelaipg/intel-optimized-tensorflow:1.11.0-mkl-py3 images across the board

### LINKED ISSUE #388: Use the `Intel` optimized `Tensorflow` images for all templates that require `Tensorflow`.
Now that `Intel` optimized images for `Tensorflow` are hosted here: https://hub.docker.com/r/intelaipg/intel-optimized-tensorflow/tags/
We should use them wherever we require `Tensorflow` as a requirement.

### PR DESCRIPTION
**Pull request by ashahba**
fixes #388 

If you aren't done, please add the `wip` label until you're ready for review.

If you are adding a new template or mlt command/flag ensure that is is documented in the [docs/features.md](https://github.com/IntelAI/mlt/tree/master/docs/features.md) file.

## Reviewer Checklist

 - [ ] Do you understand it?
 - [ ] Is it correct?
 - [ ] Is it safe?
 - [ ] Is it legally compliant?
 - [ ] Is it robust?
 - [ ] Is it simple?
 - [ ] Is it tested?
 - [ ] Is it documented?
 - [ ] Is the style consistent?

See [the reviewer guide](docs/reviews.md) for more detail on each check.

### CODE REVIEW

**Comment by ashahba** [comment]
Still need to do `horovod` template.

**Comment by ashahba** [comment]
I need to look into `tf-dist-mnist` and why it's failing.
It's most likely an issue with `Tensorflow 1.9`.

**Comment by s1113950** [comment]
@ashahba what's the status of this?

**Comment by nqn** [comment]
Closing due to project deprecation

**Pull request closed without merging**
